apiVersion: apps/v1
kind: Deployment
metadata:
  name: calendar-calculator-deployment
  labels:
    app: calendar-calculator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calendar-calculator
  template:
    metadata:
      labels:
        app: calendar-calculator
    spec:
      containers:
      - name: calendar-calculator
        image: calendar-calculator:latest
        ports:
        - containerPort: 8080
        imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: calendar-calculator-service
spec:
  selector:
    app: calendar-calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
